config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.shortcuts import render
from django.urls import path
from . import views
app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('guito', views.guito_page_view, name="guito"),
    path('fotos', views.fotos_page_view, name="fotos")
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render



def guito_page_view(request):
    context = {
        'raca': "Yorkshire Terrier"
    }
    return render(request, 'website/guito.html', context)

def home_page_view(request):
    context = {
        'data': "24/08/2019",
        'cor': "Preto e Castanho",
        'porte': "Pequeno",
        'carat': "Fotogénico"
    }
    return render(request, 'website/home.html', context)


def fotos_page_view(request):

    return render(request, 'website/fotos.html')


# Create your views here.

website/templates/website/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>A Meaningful Page Title</title>
     {% load static %}
    <link rel="stylesheet" href="{%  static  'website/css/base.css' %}">
</head>
<body>
    <header class="jumbotron text-center">
        <h1>Guito</h1>
        <p>Yorkshire Terrier</p>
        <nav>
            <a href="{% url 'website:home' %}" class="btn btn-info">Inicio</a>
            <a href="{% url 'website:guito' %}" class="btn btn-info">Guito</a>
            <a href="{% url 'website:fotos' %}" class="btn btn-info">Fotos</a>
        </nav>
    </header>
    <article class="container">
        <main class="col-sm-6">
	        {% block main %}
	        {% endblock main %}
        </main>
        <aside class="col-sm-6">
            {% load static %}
            <img src="{% static 'website/img/Guito.jpeg' %}">
        </aside>
    </article>
    <footer>Universidade Lusofona</footer>
</body>

website/templates/website/fotos.html
{% extends 'website/base.html' %}

{% block main %}
{% load static %}
    <h3>Inicio</h3>
    <p>Esta é a galeria de fotos do menino</p>
<img src="{% static 'website/img/guito1.jpeg' %}">
<img src="{% static 'website/img/guito2.jpeg' %}">
<img src="{% static 'website/img/guito3.jpeg' %}">
{% endblock %}

website/templates/website/guito.html
<!-- home.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>Guito</h3>
    <p>Guito é um {{ raca }} muito social</p>
{% endblock %}

website/templates/website/home.html
<!-- home.html -->

{% extends 'website/base.html' %}

{% block main %}
    <h3>Inicio</h3>
    <p>Aqui podemos conhecer um bocadinho melhor o Guito.</p>
    <p>Data de nascimento: {{ data }}</p>
    <p>Cor: {{ cor }}</p>
    <p>Porte: {{ porte }}</p>
    <p>Caraterísticas: {{ carat }}</p>
{% endblock %}